trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: ls -R  $(System.DefaultWorkingDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: java -version
      - bash: node --version
      - bash: python --version
      - bash: mvn -version
      - bash: ls -R $(Build.ArtifactStagingDirectory)